sequenceDiagram
Title: 0.6: New note in Single page

participant browser
participant server

browser->server: GET https://studies.cs.helsinki.fi/exampleapp/spa
activate server
server-->>browser: HTML document
deactivate server
browser->server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
activate server
server-->>browser: the css file
deactivate server
browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/spa.js
activate server
server-->>browser: the JavaScript file
deactivate server

Note right of browser: The browser starts executing the JavaScript code that fetches the JSON from the server

browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
activate server
server-->>browser: [{content: "random note!!!!!!!!!!!!!!!!!!!!!!!!!!!!!", date: "2024-05-29T21:45:59.120Z"},…]
deactivate server

Note right of browser: The browser executes the callback function that renders the notes

browser->server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa
Note right of browser: browser js event handler stop to reload the page
activate server
server-->>browser: {content: "test", date: "2024-05-30T09:06:02.643Z"}
deactivate server

Note right of browser: Instead of reloading the page browser executes the event handler that renders notes to display


